import type { Metadata } from "next";
import { Iceberg } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const iceberg = Iceberg({
  variable: "--font-iceberg-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "FIFA World Cup 2026",
  description: "Generated by FLWMSTR",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${iceberg.variable}`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
